### ISSUE TITLE
A question of training DIMP50 on TrackingNet

### ISSUE THREAD

**Issue by bigbigrabbit** [visionml/pytracking#100]
When I  training DIMP50 on TrackingNet,I meet this question,anyone can help me?please!

Restarting training from last epoch ...
No matching checkpoint file found
ERROR: Could not read image "/media/ddww/My Passport/tracking/TrackingNet/TRAIN_3/frames/bJqhWaDN0hQ_1/448.jpg"
[Errno 2] No such file or directory: '/media/ddww/My Passport/tracking/TrackingNet/TRAIN_3/frames/bJqhWaDN0hQ_1/448.jpg'
ERROR: Could not read image "/media/ddww/My Passport/tracking/TrackingNet/TRAIN_3/frames/bJqhWaDN0hQ_1/442.jpg"
[Errno 2] No such file or directory: '/media/ddww/My Passport/tracking/TrackingNet/TRAIN_3/frames/bJqhWaDN0hQ_1/442.jpg'
ERROR: Could not read image "/media/ddww/My Passport/tracking/TrackingNet/TRAIN_3/frames/bJqhWaDN0hQ_1/446.jpg"
[Errno 2] No such file or directory: '/media/ddww/My Passport/tracking/TrackingNet/TRAIN_3/frames/bJqhWaDN0hQ_1/446.jpg'
ERROR: Could not read image "/media/ddww/My Passport/tracking/TrackingNet/TRAIN_3/frames/bJqhWaDN0hQ_1/466.jpg"
[Errno 2] No such file or directory: '/media/ddww/My Passport/tracking/TrackingNet/TRAIN_3/frames/bJqhWaDN0hQ_1/466.jpg'
ERROR: Could not read image "/media/ddww/My Passport/tracking/TrackingNet/TRAIN_3/frames/bJqhWaDN0hQ_1/473.jpg"
[Errno 2] No such file or directory: '/media/ddww/My Passport/tracking/TrackingNet/TRAIN_3/frames/bJqhWaDN0hQ_1/473.jpg'
ERROR: Could not read image "/media/ddww/My Passport/tracking/TrackingNet/TRAIN_3/frames/bJqhWaDN0hQ_1/457.jpg"
[Errno 2] No such file or directory: '/media/ddww/My Passport/tracking/TrackingNet/TRAIN_3/frames/bJqhWaDN0hQ_1/457.jpg'
Training crashed at epoch 1
Traceback for the error!
Traceback (most recent call last):
  File "../ltr/trainers/base_trainer.py", line 70, in train
    self.train_epoch()
  File "../ltr/trainers/ltr_trainer.py", line 76, in train_epoch
    self.cycle_dataset(loader)
  File "../ltr/trainers/ltr_trainer.py", line 50, in cycle_dataset
    for i, data in enumerate(loader, 1):
  File "/home/ddww/anaconda3/envs/pytracking/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 346, in __next__
    data = self.dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/ddww/anaconda3/envs/pytracking/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ddww/anaconda3/envs/pytracking/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "../ltr/data/sampler.py", line 294, in __getitem__
    return self.processing(data)
  File "../ltr/data/processing.py", line 294, in __call__
    self.search_area_factor, self.output_sz)
  File "../ltr/data/processing_utils.py", line 116, in jittered_center_crop
    for f, a in zip(frames, box_extract)]
  File "../ltr/data/processing_utils.py", line 116, in <listcomp>
    for f, a in zip(frames, box_extract)]
  File "../ltr/data/processing_utils.py", line 42, in sample_target
    x2_pad = max(x2-im.shape[1]+1, 0)
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by 983632847** [comment]
@bigbigrabbit  Could you share the TrackingNet dataset on Baidu Yun. Thanks a lot. As you known, many Chinese can not access the Google Drive.

**Comment by bigbigrabbit** [comment]
I·ll have a try.

**Comment by 983632847** [comment]
@bigbigrabbit  Thanks for your commitment. I will focus on it.

**Comment by bigbigrabbit** [comment]
Traceback (most recent call last):
  File "../ltr/trainers/base_trainer.py", line 70, in train
    self.train_epoch()
  File "../ltr/trainers/ltr_trainer.py", line 76, in train_epoch
    self.cycle_dataset(loader)
  File "../ltr/trainers/ltr_trainer.py", line 50, in cycle_dataset
    for i, data in enumerate(loader, 1):
  File "/home/ddww/anaconda3/envs/pytracking/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 346, in __next__
    data = self.dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/ddww/anaconda3/envs/pytracking/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ddww/anaconda3/envs/pytracking/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "../ltr/data/sampler.py", line 251, in __getitem__
    seq_info_dict = dataset.get_sequence_info(seq_id)
  File "../ltr/dataset/lasot.py", line 102, in get_sequence_info
    visible = self._read_target_visible(seq_path) & valid.byte()
  File "../ltr/dataset/lasot.py", line 84, in _read_target_visible
    out_of_view = torch.ByteTensor([int(v) for v in list(csv.reader(f))[0]])
_csv.Error: line contains NULL byte



Traceback (most recent call last):
  File "../ltr/trainers/base_trainer.py", line 70, in train
    self.train_epoch()
  File "../ltr/trainers/ltr_trainer.py", line 76, in train_epoch
    self.cycle_dataset(loader)
  File "../ltr/trainers/ltr_trainer.py", line 50, in cycle_dataset
    for i, data in enumerate(loader, 1):
  File "/home/ddww/anaconda3/envs/pytracking/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 346, in __next__
    data = self.dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/ddww/anaconda3/envs/pytracking/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ddww/anaconda3/envs/pytracking/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "../ltr/data/sampler.py", line 251, in __getitem__
    seq_info_dict = dataset.get_sequence_info(seq_id)
  File "../ltr/dataset/lasot.py", line 99, in get_sequence_info
    bbox = self._read_bb_anno(seq_path)
  File "../ltr/dataset/lasot.py", line 73, in _read_bb_anno
    gt = pandas.read_csv(bb_anno_file, delimiter=',', header=None, dtype=np.float32, na_filter=False, low_memory=False).values
  File "/home/ddww/anaconda3/envs/pytracking/lib/python3.7/site-packages/pandas/io/parsers.py", line 685, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/ddww/anaconda3/envs/pytracking/lib/python3.7/site-packages/pandas/io/parsers.py", line 457, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/home/ddww/anaconda3/envs/pytracking/lib/python3.7/site-packages/pandas/io/parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "/home/ddww/anaconda3/envs/pytracking/lib/python3.7/site-packages/pandas/io/parsers.py", line 1135, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/ddww/anaconda3/envs/pytracking/lib/python3.7/site-packages/pandas/io/parsers.py", line 1917, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 545, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file

**Comment by bigbigrabbit** [comment]
I tried it, But I found that Baiduyun can share only 3000 files one time. There are too much files（pictures of 1.7T） to transform，so it's difficult for me.I am so sorry I can't help you. Maybe you can buy a VPN to download this dateset. ------------------ 原始邮件 ------------------
发件人: "983632847"<notifications@github.com>
发送时间: 2019年12月3日(星期二) 下午3:18
收件人: "visionml/pytracking"<pytracking@noreply.github.com>;
抄送: "zhaoluping"<908010028@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [visionml/pytracking] A question of training DIMP50 onTrackingNet (#100)



@bigbigrabbit  Thanks for your commitment. I will focus on it.
 
&mdash;
