### ISSUE TITLE
Have some problem in VOT Integration,ask for help

### ISSUE THREAD

**Issue by candy1119** [visionml/pytracking#106]
Hi,
Thanks to your great works and useful codes!
I just install VOT Integration,it success when test the example 'NCC'.But when i test dimp,there are some proble.
 >> run_test
Initializing workspace ...
Checking for toolkit updates on GitHub.
Verifying native components ...
Testing TraX protocol support for tracker DiMP.
CLIENT: Creating process /home/itsdp/anaconda2/envs/pytracking/bin/python3.6 -c "import sys; sys.path.append('/opt/pytracking-master1010/pytracking');sys.path.append('/opt/vot-toolkit/native/trax/support/python');import run_vot;run_vot.run_vot('dimp', 'dimp50_vot', debug=0)"
CLIENT: Working directory is /tmp/tp3d9cff4a_1390_4ffd_8d84_b4cbd216c9f2
CLIENT: Starting process
CLIENT: Setting up TraX with standard streams connection
Traceback (most recent call last):
  File "/opt/pytracking-master1010/pytracking/../pytracking/VOT/vot.py", line 17, in <module>
    import trax
  File "/home/itsdp/.local/lib/python3.6/site-packages/trax/__init__.py", line 18, in <module>
    from trax import backend
  File "/home/itsdp/.local/lib/python3.6/site-packages/trax/backend.py", line 25, in <module>
    import jax
ModuleNotFoundError: No module named 'jax'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/pytracking-master1010/pytracking/run_vot.py", line 13, in run_vot
    tracker = Tracker(tracker_name, tracker_param, run_id)
  File "/opt/pytracking-master1010/pytracking/../pytracking/evaluation/tracker.py", line 28, in __init__
    tracker_module = importlib.import_module('pytracking.tracker.{}'.format(self.name))
  File "/home/itsdp/anaconda2/envs/pytracking/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/opt/pytracking-master1010/pytracking/../pytracking/tracker/dimp/__init__.py", line 1, in <module>
    from .dimp import DiMP
  File "/opt/pytracking-master1010/pytracking/../pytracking/tracker/dimp/dimp.py", line 1, in <module>
    from pytracking.tracker.base import BaseTracker
  File "/opt/pytracking-master1010/pytracking/../pytracking/tracker/base/__init__.py", line 1, in <module>
    from .basetracker import BaseTracker
  File "/opt/pytracking-master1010/pytracking/../pytracking/tracker/base/basetracker.py", line 11, in <module>
    from pytracking.VOT import vot
  File "/opt/pytracking-master1010/pytracking/../pytracking/VOT/vot.py", line 19, in <module>
    raise Exception('TraX support not found. Please add trax module to Python path.')
Exception: TraX support not found. Please add trax module to Python path.
CLIENT: Flushing streams
CLIENT: Process should be terminated.
CLIENT: Stopping logger.
CLIENT: Unable to establish connection.
CLIENT: Tracker exited (exit code 1)
CLIENT: Cleaning up.
CLIENT: Stopping logger thread
CLIENT: Trying to stop process using protocol.
Tracker execution interrupted: Unable to establish connection.
TraX support not detected.
错误使用 tracker_load (line 127)
Tracker has not passed the TraX support test.

出错 run_test (line 8)
tracker = tracker_load('DiMP');
I setup the latest vot and trax toolkit with the guidance of document. I wonder what is wrong with it. Thanks for your help.

**Comment by martin-danelljan** [comment]
> > > .........
> > > import trax
> > > File "/home/itsdp/.local/lib/python3.6/site-packages/trax/**init**.py", line 18, in 
> > > from trax import backend
> > > File "/home/itsdp/.local/lib/python3.6/site-packages/trax/backend.py", line 25, in 
> > > import jax
> > > ModuleNotFoundError: No module named 'jax'

Hi. Maybe try `pip install jax`
