### ISSUE TITLE
run run_webcam.py error 

### ISSUE THREAD

**Issue by guangzou** [visionml/pytracking#153]
Traceback (most recent call last):
  File "..\pytracking\evaluation\environment.py", line 58, in env_settings
    env_module = importlib.import_module(env_module_name)
  File "D:\DevelopTools\Anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "..\pytracking\evaluation\local.py", line 13
    settings.network_path = 'D:\Project\PythonProject\xiao_power-pytracking-master\pytracking\pytracking/networks/'    # Where tracking networks are stored.
                           ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 24-25: truncated \xXX escape

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_webcam.py", line 41, in <module>
    main()
  File "run_webcam.py", line 37, in main
    run_webcam(args.tracker_name, args.tracker_param, args.debug, visdom_info)
  File "run_webcam.py", line 21, in run_webcam
    tracker = Tracker(tracker_name, tracker_param)
  File "..\pytracking\evaluation\tracker.py", line 54, in __init__
    env = env_settings()
  File "..\pytracking\evaluation\environment.py", line 66, in env_settings
    'Then try to run again.'.format(env_file))
RuntimeError: YOU HAVE NOT SETUP YOUR local.py!!!
 Go to "..\pytracking\evaluation\local.py" and set all the paths you need. Then try to run again.

**Comment by goutamgmb** [comment]
As mentioned in the error message, the problem is the use of special character '\' in network path in local.py line 13. See https://stackoverflow.com/questions/1347791/unicode-error-unicodeescape-codec-cant-decode-bytes-cannot-open-text-file for more details.
