### ISSUE TITLE
cudatoolkit10.0 is required in the install.sh ,But libcudart.so.9.0 import error is reported

### ISSUE THREAD

**Issue by GMonster0905** [visionml/pytracking#166]
command : python run_tracker.py dimp dimp50 --dataset_name vot --debug 8
debug information >>
Evaluating    1 trackers on    60 sequences
Tracker: dimp dimp50 None ,  Sequence: ants1
Setting up a new session...
/home/pcl/.conda/envs/pytracking/lib/python3.8/site-packages/torch/nn/functional.py:2503: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  warnings.warn("Default upsampling behavior when mode={} is changed "
Using /tmp/torch_extensions as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /tmp/torch_extensions/_prroi_pooling/build.ninja...
Building extension module _prroi_pooling...
ninja: no work to do.
Loading extension module _prroi_pooling...
Traceback (most recent call last):
  File "../ltr/external/PreciseRoIPooling/pytorch/prroi_pool/functional.py", line 30, in _import_prroi_pooling
    _prroi_pooling = load_extension(
  File "/home/pcl/.conda/envs/pytracking/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 670, in load
    return _jit_compile(
  File "/home/pcl/.conda/envs/pytracking/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 877, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/home/pcl/.conda/envs/pytracking/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1088, in _import_module_from_library
    return imp.load_module(module_name, file, path, description)
  File "/home/pcl/.conda/envs/pytracking/lib/python3.8/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/pcl/.conda/envs/pytracking/lib/python3.8/imp.py", line 342, in load_dynamic
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 657, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 556, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1101, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: libcudart.so.9.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_tracker.py", line 65, in <module>
    main()
  File "run_tracker.py", line 60, in main
    run_tracker(args.tracker_name, args.tracker_param, args.runid, args.dataset_name, seq_name, args.debug,
  File "run_tracker.py", line 37, in run_tracker
    run_dataset(dataset, trackers, debug, threads, visdom_info=visdom_info)
  File "../pytracking/evaluation/running.py", line 145, in run_dataset
    run_sequence(seq, tracker_info, debug=debug, visdom_info=visdom_info)
  File "../pytracking/evaluation/running.py", line 97, in run_sequence
    output = tracker.run_sequence(seq, debug=debug, visdom_info=visdom_info)
  File "../pytracking/evaluation/tracker.py", line 148, in run_sequence
    output = self._track_sequence(tracker, seq, init_info)
  File "../pytracking/evaluation/tracker.py", line 185, in _track_sequence
    out = tracker.initialize(image, init_info)
  File "../pytracking/tracker/dimp/dimp.py", line 84, in initialize
    self.init_classifier(init_backbone_feat)
  File "../pytracking/tracker/dimp/dimp.py", line 573, in init_classifier
    self.target_filter, _, losses = self.net.classifier.get_filter(x, target_boxes, num_iter=num_iter,
  File "../ltr/models/target_classifier/linear_filter.py", line 97, in get_filter
    weights = self.filter_initializer(feat, bb)
  File "/home/pcl/.conda/envs/pytracking/lib/python3.8/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "../ltr/models/target_classifier/initializer.py", line 164, in forward
    weights = self.filter_pool(feat, bb)
  File "/home/pcl/.conda/envs/pytracking/lib/python3.8/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "../ltr/models/target_classifier/initializer.py", line 45, in forward
    return self.prroi_pool(feat, roi1)
  File "/home/pcl/.conda/envs/pytracking/lib/python3.8/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "../ltr/external/PreciseRoIPooling/pytorch/prroi_pool/prroi_pool.py", line 28, in forward
    return prroi_pool2d(features, rois, self.pooled_height, self.pooled_width, self.spatial_scale)
  File "../ltr/external/PreciseRoIPooling/pytorch/prroi_pool/functional.py", line 44, in forward
    _prroi_pooling = _import_prroi_pooling()
  File "../ltr/external/PreciseRoIPooling/pytorch/prroi_pool/functional.py", line 36, in _import_prroi_pooling
    raise ImportError('Can not compile Precise RoI Pooling library.')
ImportError: Can not compile Precise RoI Pooling library.

**Comment by GMonster0905** [comment]
I check the install.sh, there is a line  "conda install -y pytorch torchvision cudatoolkit=10.0 -c pytorch". But when compiling the precie ROI Pooling, a libcudart.so.9.0 import error is reported. I tried "conda install -c anaconda cudatoolkit==9.0" but not work and  conda conflict is found.

**Comment by GMonster0905** [comment]
this problem can be solved by changing the target of symbolic link "cuda" in /usr/local/  from cuda9.0 to cuda10.0, compatible to the cudatoolkit version in the conda env.
