### ISSUE TITLE
Exception: Could not read file /Basketball/groundtruth_rect.txt

### ISSUE THREAD

**Issue by XiaoBai-collab** [visionml/pytracking#174]
When I run run_tracker, I encountered an error as follows:
~/PycharmProjects/ObjectTrackingCode/DLCode/pytracking/pytracking$ python run_tracker.py atom default --dataset_name otb --sequence Soccer --debug 0 --threads 0
Traceback (most recent call last):
  File "run_tracker.py", line 65, in <module>
    main()
  File "run_tracker.py", line 61, in main
    args.threads, {'use_visdom': args.use_visdom, 'server': args.visdom_server, 'port': args.visdom_port})
  File "run_tracker.py", line 30, in run_tracker
    dataset = get_dataset(dataset_name)
  File "../pytracking/evaluation/datasets.py", line 60, in get_dataset
    dset.extend(load_dataset(name))
  File "../pytracking/evaluation/datasets.py", line 53, in load_dataset
    return dataset.get_sequence_list()
  File "../pytracking/evaluation/otbdataset.py", line 23, in get_sequence_list
    return SequenceList([self._construct_sequence(s) for s in self.sequence_info_list])
  File "../pytracking/evaluation/otbdataset.py", line 23, in <listcomp>
    return SequenceList([self._construct_sequence(s) for s in self.sequence_info_list])
  File "../pytracking/evaluation/otbdataset.py", line 42, in _construct_sequence
    ground_truth_rect = load_text(str(anno_path), delimiter=(',', None), dtype=np.float64, backend='numpy')
  File "../pytracking/utils/load_text.py", line 39, in load_text
    return load_text_numpy(path, delimiter, dtype)
  File "../pytracking/utils/load_text.py", line 14, in load_text_numpy
    raise Exception('Could not read file {}'.format(path))
Exception: Could not read file /Basketball/groundtruth_rect.txt

How should I solve it?

**Comment by goutamgmb** [comment]
I think you haven't set the path to OTB dataset ( self.otb_path variable) in pytracking.evaluation.local.py file.
