### ISSUE TITLE
run_webcam.py No module named 'ltr.admin.local' ltr.admin.local (solved)

### ISSUE THREAD

**Issue by cyysky** [visionml/pytracking#185]
import pytracker
python run_webcam.py dimp super_dimp
Traceback (most recent call last):
  File "run_webcam.py", line 41, in <module>
    main()
  File "run_webcam.py", line 37, in main
    run_webcam(args.tracker_name, args.tracker_param, args.debug, visdom_info)
  File "run_webcam.py", line 22, in run_webcam
    tracker.run_webcam(debug, visdom_info)
  File "../pytracking/evaluation/tracker.py", line 376, in run_webcam
    tracker = MultiObjectWrapper(self.tracker_class, params, self.visdom, fast_load=True)
  File "../pytracking/evaluation/multi_object_wrapper.py", line 21, in __init__
    self.tracker_copy.initialize_features()
  File "../pytracking/tracker/dimp/dimp.py", line 22, in initialize_features
    self.params.net.initialize()
  File "../pytracking/features/net_wrappers.py", line 53, in initialize
    super().initialize()
  File "../pytracking/features/net_wrappers.py", line 37, in initialize
    self.load_network()
  File "../pytracking/features/net_wrappers.py", line 31, in load_network
    self.net = load_network(self.net_path, **self.net_kwargs)
  File "../pytracking/utils/loading.py", line 31, in load_network
    net, _ = ltr_loading.load_network(path_full, **kwargs)
  File "../ltr/admin/loading.py", line 79, in load_network
    checkpoint_dict = torch_load_legacy(checkpoint_path)
  File "../ltr/admin/loading.py", line 122, in torch_load_legacy
    _setup_legacy_env()
  File "../ltr/admin/loading.py", line 140, in _setup_legacy_env
    importlib.import_module('ltr.admin.' + m)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'ltr.admin.local'

and I resolved by manual added a local.py a already uploaded this file.

[local.zip](https://github.com/visionml/pytracking/files/5287094/local.zip)

**Comment by martin-danelljan** [comment]
Great!
