### ISSUE TITLE
a problem of vot dataset eval , need help.

### ISSUE THREAD

**Issue by kuiran** [visionml/pytracking#193]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/kuiran/github/pytracking/pytracking/run_vot.py", line 19, in run_vot
    tracker.run_vot()
  File "/home/kuiran/github/pytracking/pytracking/../pytracking/evaluation/tracker.py", line 621, in run_vot
    handle = vot.VOT("polygon")
  File "/home/kuiran/github/pytracking/pytracking/../pytracking/evaluation/vot.py", line 92, in __init__
    options = trax.server.ServerOptions(region_format, trax.image.PATH)
AttributeError: module 'trax.server' has no attribute 'ServerOptions'
Exception ignored in: <function VOT.__del__ at 0x7fb0daca39e0>
Traceback (most recent call last):
  File "/home/kuiran/github/pytracking/pytracking/../pytracking/evaluation/vot.py", line 173, in __del__
    self.quit()
  File "/home/kuiran/github/pytracking/pytracking/../pytracking/evaluation/vot.py", line 165, in quit
    self._trax.quit()
AttributeError: 'VOT' object has no attribute '_trax'

when in matlab2020 run run_test.m the problem happened.How to fix it.

**Comment by yxxxqqq** [comment]
did you solve it? I meet the same problem.

**Comment by goutamgmb** [comment]
Could you post the exact command you are running? Also are you using the vot2020 python toolkit, or the older matlab toolkit?
