### ISSUE TITLE
Can this project work with CPU?

### ISSUE THREAD

**Issue by RIKOYUKI** [visionml/pytracking#23]
/home/l/anaconda3/envs/pytorch/bin/python3 /home/l/Documents/17ICCV2019/projects/ATOM/pytracking/pytracking/run_tracker.py atom default
Tracker: atom default None ,  Sequence: ants1
Using /tmp/torch_extensions as PyTorch extensions root...
Traceback (most recent call last):
  File "/home/l/Documents/17ICCV2019/projects/ATOM/pytracking/pytracking/run_tracker.py", line 79, in <module>
    main()
  File "/home/l/Documents/17ICCV2019/projects/ATOM/pytracking/pytracking/run_tracker.py", line 75, in main
    run_tracker(args.tracker_name, args.tracker_param, args.runid, args.dataset, args.sequence, args.debug, args.threads)
  File "/home/l/Documents/17ICCV2019/projects/ATOM/pytracking/pytracking/run_tracker.py", line 60, in run_tracker
    run_dataset(dataset, trackers, debug, threads)
  File "/home/l/Documents/17ICCV2019/projects/ATOM/pytracking/pytracking/../pytracking/evaluation/running.py", line 54, in run_dataset
    run_sequence(seq, tracker_info, debug=debug)
  File "/home/l/Documents/17ICCV2019/projects/ATOM/pytracking/pytracking/../pytracking/evaluation/running.py", line 21, in run_sequence
    tracked_bb, exec_times = tracker.run(seq, debug=debug)
  File "/home/l/Documents/17ICCV2019/projects/ATOM/pytracking/pytracking/../pytracking/evaluation/tracker.py", line 58, in run
    output_bb, execution_times = tracker.track_sequence(seq)
  File "/home/l/Documents/17ICCV2019/projects/ATOM/pytracking/pytracking/../pytracking/tracker/base/basetracker.py", line 34, in track_sequence
    self.initialize(image, sequence.init_state)
  File "/home/l/Documents/17ICCV2019/projects/ATOM/pytracking/pytracking/../pytracking/tracker/atom/atom.py", line 31, in initialize
    self.initialize_features()
  File "/home/l/Documents/17ICCV2019/projects/ATOM/pytracking/pytracking/../pytracking/tracker/atom/atom.py", line 19, in initialize_features
    self.params.features.initialize()
  File "/home/l/Documents/17ICCV2019/projects/ATOM/pytracking/pytracking/../pytracking/features/extractor.py", line 16, in initialize
    f.initialize()
  File "/home/l/Documents/17ICCV2019/projects/ATOM/pytracking/pytracking/../pytracking/features/deep.py", line 95, in initialize
    self.net, _ = load_network(net_path_full, backbone_pretrained=False)
  File "/home/l/Documents/17ICCV2019/projects/ATOM/pytracking/pytracking/../ltr/admin/loading.py", line 70, in load_network
    net = net_constr.get()
  File "/home/l/Documents/17ICCV2019/projects/ATOM/pytracking/pytracking/../ltr/admin/model_constructor.py", line 43, in get
    net_module = importlib.import_module(self.fun_module)
  File "/home/l/anaconda3/envs/pytorch/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 936, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
Detected CUDA files, patching ldflags
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/home/l/Documents/17ICCV2019/projects/ATOM/pytracking/pytracking/../ltr/models/bbreg/__init__.py", line 1, in <module>
    from .atom_iou_net import AtomIoUNet
  File "/home/l/Documents/17ICCV2019/projects/ATOM/pytracking/pytracking/../ltr/models/bbreg/atom_iou_net.py", line 4, in <module>
    from ltr.external.PreciseRoIPooling.pytorch.prroi_pool import PrRoIPool2D
  File "/home/l/Documents/17ICCV2019/projects/ATOM/pytracking/pytracking/../ltr/external/PreciseRoIPooling/pytorch/prroi_pool/__init__.py", line 12, in <module>
    from .prroi_pool import *
  File "/home/l/Documents/17ICCV2019/projects/ATOM/pytracking/pytracking/../ltr/external/PreciseRoIPooling/pytorch/prroi_pool/prroi_pool.py", line 14, in <module>
    from .functional import prroi_pool2d
  File "/home/l/Documents/17ICCV2019/projects/ATOM/pytracking/pytracking/../ltr/external/PreciseRoIPooling/pytorch/prroi_pool/functional.py", line 22, in <module>
    verbose=True
  File "/home/l/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 645, in load
    is_python_module)
  File "/home/l/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 815, in _jit_compile
    with_cuda=None)
  File "/home/l/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 845, in _write_ninja_file_and_build
    verbose)
  File "/home/l/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 910, in _prepare_ldflags
    extra_ldflags.append('-L{}'.format(_join_cuda_home('lib64')))
  File "/home/l/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1122, in _join_cuda_home
    raise EnvironmentError('CUDA_HOME environment variable is not set. '
OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.

**Comment by martin-danelljan** [comment]
The Precise ROI pool requires CUDA. All other components should run fine on CPU. Try running ECO instead of ATOM and set the `params.use_gpu = False` in the parameter file.

If you want to try ATOM, you need to turn of the IoUNet and use the classifier for scale estimation.

**Comment by RIKOYUKI** [comment]
Thank for your instructions!
