### ISSUE TITLE
Problem LTR Training

### ISSUE THREAD

**Issue by grablerm** [visionml/pytracking#236]
Hi,

i do have a problem to do your offered LTR training. I set up the environment and put the paths of the datasets and pretrained networks. However i get the error that there is no matching checkpoint file. I want to train on a COCO dataset and track with ATOM. Do you know which files i maybe have to include (probably into the pretrained networks folder?)
Thanks in advance and Best regards.

**Comment by martin-danelljan** [comment]
What training script do you try to run and what is the error?

**Comment by grablerm** [comment]
i run _python run_training.py bbreg atom_ and the the error is:

No matching checkpoint file found
Training crashed at epoch 1
Traceback for the error!
Traceback (most recent call last):
  File "../ltr/trainers/base_trainer.py", line 70, in train
    self.train_epoch()
  File "../ltr/trainers/ltr_trainer.py", line 80, in train_epoch
    self.cycle_dataset(loader)
  File "../ltr/trainers/ltr_trainer.py", line 52, in cycle_dataset
    for i, data in enumerate(loader, 1):
  File "/usr/local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.7/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "../ltr/data/sampler.py", line 106, in __getitem__
    seq_info_dict = dataset.get_sequence_info(seq_id)
  File "../ltr/dataset/coco_seq.py", line 120, in get_sequence_info
    mask = torch.Tensor(self.coco_set.annToMask(anno)).unsqueeze(dim=0)
  File "/usr/local/lib/python3.7/site-packages/pycocotools/coco.py", line 431, in annToMask
    rle = self.annToRLE(ann)
  File "/usr/local/lib/python3.7/site-packages/pycocotools/coco.py", line 416, in annToRLE
    rles = maskUtils.frPyObjects(segm, h, w)
  File "pycocotools/_mask.pyx", line 292, in pycocotools._mask.frPyObjects
IndexError: list index out of range

**Comment by martin-danelljan** [comment]
Hi. The checkpoint is not the problem. The problem is the loading of the COCO dataset. Have you downloaded it and set the paths to it correctly?
