### ISSUE TITLE
ImportError: cannot import name 'int_classes' from 'torch._six' 

### ISSUE THREAD

**Issue by chetanpandey1266** [visionml/pytracking#264]
I was running your code using run_experiment script 

```python
python run_experiment.py myexperiments uav_test 
```
And I am getting this error
```console
Traceback (most recent call last):
  File "run_experiment.py", line 10, in <module>
    from pytracking.evaluation.running import run_dataset
  File "../pytracking/__init__.py", line 7, in <module>
    from pytracking.run_tracker import run_tracker
  File "../pytracking/run_tracker.py", line 9, in <module>
    from pytracking.evaluation import get_dataset
  File "../pytracking/evaluation/__init__.py", line 1, in <module>
    from .data import Sequence
  File "../pytracking/evaluation/data.py", line 3, in <module>
    from ltr.data.image_loader import imread_indexed
  File "../ltr/data/__init__.py", line 1, in <module>
    from .loader import LTRLoader
  File "../ltr/data/loader.py", line 5, in <module>
    from torch._six import string_classes, int_classes
ImportError: cannot import name 'int_classes' from 'torch._six' (/usr/local/lib/python3.7/dist-packages/torch/_six.py)

```

Can someone suggest how to fix this

**Comment by martin-danelljan** [comment]
Hi. Are you using pytorch 1.9? I think there is an incompatibility issue. Will fix this soon. In the meantime you can use 1.8.

**Comment by chetanpandey1266** [comment]
Okay I'll try this.
