### ISSUE TITLE
cannot import name 'int_classes' from 'torch._six'

### ISSUE THREAD

**Issue by angaio** [visionml/pytracking#272]
Hi:
     when I run the example on win10,cuda10,the following errors occurs.
     Does anyone have the same error?what's problem?

Traceback (most recent call last):
  File "run_webcam.py", line 9, in <module>
    from pytracking.evaluation import Tracker
  File "..\pytracking\__init__.py", line 7, in <module>
    from pytracking.run_tracker import run_tracker
  File "..\pytracking\run_tracker.py", line 9, in <module>
    from pytracking.evaluation import get_dataset
  File "..\pytracking\evaluation\__init__.py", line 1, in <module>
    from .data import Sequence
  File "..\pytracking\evaluation\data.py", line 3, in <module>
    from ltr.data.image_loader import imread_indexed
  File "..\ltr\data\__init__.py", line 1, in <module>
    from .loader import LTRLoader
  File "..\ltr\data\loader.py", line 5, in <module>
    from torch._six import string_classes, int_classes
ImportError: cannot import name 'int_classes' from 'torch._six'

**Comment by tm9161** [comment]
In pytorch 1.9 'int_classes variable in torch._six was removed . https://github.com/facebookresearch/TimeSformer/pull/47
I have the same problem and use this code instead. 

from torch._six import string_classes
int_classes = (bool, int)

**Comment by angaio** [comment]
Ok,Thank you!
I just try to comment the sentence "from torch._six import string_classes, int_classes",It becomes ok！
As below:
import collections
#from torch._six import string_classes, int_classes
from pytracking import TensorDict, TensorList
