### ISSUE TITLE
run_video.py has an AttributeError

### ISSUE THREAD

**Issue by wangjiannb** [visionml/pytracking#288]
my instruction is
`python run_video.py keep_track default /home/mark/code_myself/video.mp4`

but the output of terminal is
`Traceback (most recent call last):
  File "/home/mark/code_demo/pytracking/pytracking/run_video.py", line 38, in <module>
    main()
  File "/home/mark/code_demo/pytracking/pytracking/run_video.py", line 34, in main
    run_video(args.tracker_name, args.tracker_param,args.videofile, args.optional_box, args.debug, args.save_results)
  File "/home/mark/code_demo/pytracking/pytracking/run_video.py", line 20, in run_video
    tracker.run_video(videofilepath=videofile, optional_box=optional_box, debug=debug, save_results=save_results)
  File "/home/mark/code_demo/pytracking/pytracking/../pytracking/evaluation/tracker.py", line 299, in run_video
    tracker.initialize(frame, _build_init_info(init_state))
  File "/home/mark/code_demo/pytracking/pytracking/../pytracking/evaluation/multi_object_wrapper.py", line 117, in initialize
    out = self.trackers[obj_id].initialize(image, init_info_split[obj_id])
  File "/home/mark/code_demo/pytracking/pytracking/../pytracking/tracker/keep_track/keep_track.py", line 91, in initialize
    self.init_classifier(init_backbone_feat)
  File "/home/mark/code_demo/pytracking/pytracking/../pytracking/tracker/keep_track/keep_track.py", line 802, in init_classifier
    x = self.get_classification_features(init_backbone_feat)
  File "/home/mark/code_demo/pytracking/pytracking/../pytracking/tracker/keep_track/keep_track.py", line 518, in get_classification_features
    return self.net.extract_classification_feat(backbone_feat)
  File "/home/mark/code_demo/pytracking/pytracking/../pytracking/features/net_wrappers.py", line 26, in __getattr__
    raise e
  File "/home/mark/code_demo/pytracking/pytracking/../pytracking/features/net_wrappers.py", line 23, in __getattr__
    ret_val = getattr(self.net, name)
  File "/home/mark/.conda/envs/pytracking/lib/python3.9/site-packages/torch/nn/modules/module.py", line 947, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'TargetCandidateMatchingNetwork' object has no attribute 'extract_classification_feat'`

my model is pytracking/pytracking/networks/keep_track.pth.tar. Download from the google

**Comment by wangjiannb** [comment]
where can i find super_dimp_hinge model? I don't find a way to get it. Or can you give me a link? i'll be very grateful.

**Comment by 2006pmach** [comment]
Sorry my bad I meant `super_dimp_simple` you can find it [here](https://drive.google.com/file/d/1lzwdeX9HBefQwznMaX5AKAGda7tqeQtg) as explained [here](https://github.com/visionml/pytracking/blob/master/pytracking/README.md#KeepTrack).

**Comment by wangjiannb** [comment]
i change params.net from keep_track.pth.tar to super_dimp_simple.pth.tar. this question is sloved. Thank you very much!
