### ISSUE TITLE
Problems in installing pytrack on ubuntu 18.04

### ISSUE THREAD

**Issue by Alaa331** [visionml/pytracking#310]
Dear Authors,
Thanks for your amazing work. previously I used your work from other GitHub account. Alas I had to format and create new account due to a ransomware.

- The first Problem I encountered in the installation was the python version conda automatically install the version 3.9. I solved the issue by adding a python version parameter in the install.sh script.

- The second problem is the torch version, with cuda toolkit 10.0 in the script install.sh conda will install torch version 1.10.2 and this lead to the following Error:

`(pytracking_recomm) ubuntu@ubuntu-a:~/Desktop/tracking/pytrack/pytracking/pytracking$ python run_video.py dimp dimp50 14.mp4 
Traceback (most recent call last):
  File "run_video.py", line 9, in <module>
    from pytracking.evaluation import Tracker
  File "../pytracking/__init__.py", line 7, in <module>
    from pytracking.run_tracker import run_tracker
  File "../pytracking/run_tracker.py", line 9, in <module>
    from pytracking.evaluation import get_dataset
  File "../pytracking/evaluation/__init__.py", line 1, in <module>
    from .data import Sequence
  File "../pytracking/evaluation/data.py", line 3, in <module>
    from ltr.data.image_loader import imread_indexed
  File "../ltr/data/__init__.py", line 1, in <module>
    from .loader import LTRLoader
  File "../ltr/data/loader.py", line 5, in <module>
    from torch._six import string_classes, int_classes
ImportError: cannot import name 'int_classes' from 'torch._six' (/home/ubuntu/anaconda3/envs/pytracking_recomm/lib/python3.7/site-packages/torch/_six.py)
` 
In the official website of torch the version of torch supporting cuda 10 is 1.10.2 [Official torch](https://pytorch.org/get-started/previous-versions/)
I solved the issue concerning the python version but I'm stuck on torch issue I have read the  [issue](https://github.com/visionml/pytracking/issues/264) yet according the official torch website I cant install torch 1.8 with cuda 10. and cuda 10 is the key element of the project.
when trying to install torch 1.8.1 the conda couldnt find a 1.8 version for GPU 
` conda install pytorch==1.8.1 torchvision==0.9.1 torchaudio==0.8.1 cudatoolkit=10.0 -c pytorch
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/ubuntu/anaconda3/envs/pytracking_recomm

  added / updated specs:
    - cudatoolkit=10.0
    - pytorch==1.8.1
    - torchaudio==0.8.1
    - torchvision==0.9.1

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    jpeg-9b                    |       h024ee3a_2         214 KB
    ninja-1.10.2               |   py37hd09550d_3         1.5 MB
    pytorch-1.8.1              |      py3.7_cpu_0        65.9 MB  pytorch
    torchaudio-0.8.1           |             py37         4.4 MB  pytorch
    torchvision-0.9.1          |         py37_cpu        21.9 MB  pytorch
    ------------------------------------------------------------
                                           Total:        93.8 MB

The following NEW packages will be INSTALLED:

  ninja              pkgs/main/linux-64::ninja-1.10.2-py37hd09550d_3
  torchaudio         pytorch/linux-64::torchaudio-0.8.1-py37

The following packages will be DOWNGRADED:

  jpeg                                        9d-h7f8727e_0 --> 9b-h024ee3a_2
  pytorch                                1.10.2-py3.7_cpu_0 --> 1.8.1-py3.7_cpu_0
  torchvision                               0.11.3-py37_cpu --> 0.9.1-py37_cpu

Proceed ([y]/n)? 
`
and when proceeding torch cant find cuda
![image](https://user-images.githubusercontent.com/100198206/155115415-4804367b-55d3-4b04-973b-615c564743b5.png)

please note that Im using ubuntu 18.0.4 and the cuda 10 is installed and working properly. 
please edit the install.sh script and help solving the issue mentioned above.
Looking forward to hearing from you.
Best regards.

**Comment by Alaa331** [comment]
Even if I kept the original torch (from the install.sh) the following the torch is not fiding cuda
![image](https://user-images.githubusercontent.com/100198206/155122009-f81182af-009f-4e2f-a918-2441d7c98434.png)

**Comment by Alaa331** [comment]
I solved the problem by replacing cuda installation command with that command
`pip install torch==1.4.0 torchvision==0.5.0 -f https://download.pytorch.org/whl/cu100/torch_stable.html`
