### ISSUE TITLE
update script with specific library versions.

### ISSUE THREAD

**Issue by sluke17** [visionml/pytracking#317]
Hi there,

I am having problems with getting Dimp to install. Mostly with the spatial-correlation-sampler is complaining about not being able to find the right version. I have installed Ubuntu 18.04 and have followed the instructions. From what I can see, the install script will install the latest versions for each library other than the Cuda tool kit (10.0). Trying to figure out if this is my problem. Are you able to provide an install script with the specific versions of each library you have used?

Thanks

**Comment by 2006pmach** [comment]
Hey

As mentioned [here](https://github.com/visionml/pytracking/blob/master/INSTALL.md#install-spatial-correlation-sampler-only-required-for-kys-tracker) only KYS requires the spatial-correlation-sampler. Running DiMP should be possible only with the preciseROI pooling module that you have to install as described in the Readme.

If you want to try KYS or install the spatial-correlation-samples anyway. Please check the original repo linked in the Readme for compatibility with recent pytorch and cuda versions.

Otherwise I think using a recent pytorch version and the corresponding cudatoolkit according to your GPU and drivers should be fine. I haven't tried with pytorch 1.11 but 1.7 or 1.9 works fine from what I remember.

**Comment by sluke17** [comment]
Hi there, thanks for the quick reply. I get the following error when I try running the dimp 50 on an mp4 file. Does it make sense to you?

![pytorch error](https://user-images.githubusercontent.com/56849085/158222122-03f5d567-b22f-41f1-8391-36e859633e53.png)

**Comment by sluke17** [comment]
Hi, I am getting closer. I now get the following error when use this command:
sudo python -c "from pytracking.evaluation.environment import create_default_local_file; create_default_local_file()"

Produces error:
ImportError: No module named pytracking.evaluation.environment

**Comment by sluke17** [comment]
Also, if I run the webcam.py, I get the following

python run_webcam.py dimp dimp50
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-834h7bnk because the default path (/home/simon/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Traceback (most recent call last):
  File "run_webcam.py", line 41, in <module>
    main()
  File "run_webcam.py", line 37, in main
    run_webcam(args.tracker_name, args.tracker_param, args.debug, visdom_info)
  File "run_webcam.py", line 22, in run_webcam
    tracker.run_webcam(debug, visdom_info)
  File "../pytracking/evaluation/tracker.py", line 381, in run_webcam
    tracker = MultiObjectWrapper(self.tracker_class, params, self.visdom, fast_load=True)
  File "../pytracking/evaluation/multi_object_wrapper.py", line 21, in __init__
    self.tracker_copy.initialize_features()
  File "../pytracking/tracker/dimp/dimp.py", line 22, in initialize_features
    self.params.net.initialize()
  File "../pytracking/features/net_wrappers.py", line 53, in initialize
    super().initialize()
  File "../pytracking/features/net_wrappers.py", line 37, in initialize
    self.load_network()
  File "../pytracking/features/net_wrappers.py", line 31, in load_network
    self.net = load_network(self.net_path, **self.net_kwargs)
  File "../pytracking/utils/loading.py", line 31, in load_network
    net, _ = ltr_loading.load_network(path_full, **kwargs)
  File "../ltr/admin/loading.py", line 62, in load_network
    raise Exception('No matching checkpoint file found')
Exception: No matching checkpoint file found
