### ISSUE TITLE
AttributeError about dataloader

### ISSUE THREAD

**Issue by Jee-King** [visionml/pytracking#328]
Hi, could you give me some suggestions about the following error? Thx

```
pydev debugger: process 224361 is connecting
Connected to pydev debugger (build 202.7660.27)
Training:  dimp  saot
3612
2964
2380
1860
1404
2022-04-30 20:07:48.186097: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
No matching checkpoint file found
Training crashed at epoch 1
Traceback for the error!
Traceback (most recent call last):
  File "/home/iccd/Documents/SAOT-main/ltr/trainers/base_trainer.py", line 70, in train
    self.train_epoch()
  File "/home/iccd/Documents/SAOT-main/ltr/trainers/ltr_trainer.py", line 80, in train_epoch
    self.cycle_dataset(loader)
  File "/home/iccd/Documents/SAOT-main/ltr/trainers/ltr_trainer.py", line 52, in cycle_dataset
    for i, data in enumerate(loader, 1):
  File "/home/iccd/miniconda3/envs/pytracking/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/iccd/miniconda3/envs/pytracking/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 475, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/iccd/miniconda3/envs/pytracking/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/home/iccd/Documents/SAOT-main/ltr/data/loader.py", line 105, in ltr_collate_stack1
    return TensorDict({key: ltr_collate_stack1([d[key] for d in batch]) for key in batch[0]})
  File "/home/iccd/Documents/SAOT-main/ltr/data/loader.py", line 105, in <dictcomp>
    return TensorDict({key: ltr_collate_stack1([d[key] for d in batch]) for key in batch[0]})
  File "/home/iccd/Documents/SAOT-main/ltr/data/loader.py", line 113, in ltr_collate_stack1
    return [ltr_collate_stack1(samples) for samples in transposed]
  File "/home/iccd/Documents/SAOT-main/ltr/data/loader.py", line 113, in <listcomp>
    return [ltr_collate_stack1(samples) for samples in transposed]
  File "/home/iccd/Documents/SAOT-main/ltr/data/loader.py", line 113, in ltr_collate_stack1
    return [ltr_collate_stack1(samples) for samples in transposed]
  File "/home/iccd/Documents/SAOT-main/ltr/data/loader.py", line 113, in <listcomp>
    return [ltr_collate_stack1(samples) for samples in transposed]
  File "/home/iccd/Documents/SAOT-main/ltr/data/loader.py", line 91, in ltr_collate_stack1
    if torch.utils.data.dataloader.re.search('[SaUO]', elem.dtype.str) is not None:
AttributeError: module 'torch.utils.data.dataloader' has no attribute 're'
```

**Comment by laisimiao** [comment]
same question
