### ISSUE TITLE
test index error

### ISSUE THREAD

**Issue by lyt31** [visionml/pytracking#367]
Traceback (most recent call last):
  File "run_tracker.py", line 65, in <module>
    main()
  File "run_tracker.py", line 61, in main
    args.threads, {'use_visdom': args.use_visdom, 'server': args.visdom_server, 'port': args.visdom_port})
  File "run_tracker.py", line 37, in run_tracker
    run_dataset(dataset, trackers, debug, threads, visdom_info=visdom_info)
  File "../pytracking/evaluation/running.py", line 203, in run_dataset
    pool.starmap(run_sequence, param_list)
  File "/home/bobo/D/anaconda3/envs/pytracking/lib/python3.7/multiprocessing/pool.py", line 276, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/home/bobo/D/anaconda3/envs/pytracking/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
IndexError: invalid index to scalar variable.

Thank you very much for your work, how to solve this problem?

**Comment by qwerdf1223** [comment]
I have encountered the same problem as you. Have you solved it?

**Comment by 2006pmach** [comment]
What are you running exactly? Command? Can you try with `--threads 0` and see if this works?

**Comment by kranthibv** [comment]
I am running this command and getting similar kind of error in visualization in file tracker under evaluation under pytracking at line 710    
cmd: python run_tracker.py tomp tomp50 --dataset_name otb --sequence Basketball --debug 1 --threads 0

Box from boxes variable is taking a scalar value not the complete rectangle detais

Help me

**Comment by kranthibv** [comment]
python run_tracker.py tomp tomp50 --dataset_name otb --sequence Basketball --debug 1 --threads 0
Evaluating    1 trackers on     1 sequences
Tracker: tomp tomp50 None ,  Sequence: Basketball
Setting up a new session...
http://127.0.0.1:8097/env/main
!!! WARNING: Visdom could not start, so using matplotlib visualization instead !!!
!!! Start Visdom in a separate terminal window by typing 'visdom' !!!
Traceback (most recent call last):
  File "run_tracker.py", line 65, in <module>
    main()
  File "run_tracker.py", line 61, in main
    args.threads, {'use_visdom': args.use_visdom, 'server': args.visdom_server, 'port': args.visdom_port})
  File "run_tracker.py", line 37, in run_tracker
    run_dataset(dataset, trackers, debug, threads, visdom_info=visdom_info)
  File "../pytracking/evaluation/running.py", line 199, in run_dataset
    run_sequence(seq, tracker_info, debug=debug, visdom_info=visdom_info)
  File "../pytracking/evaluation/running.py", line 148, in run_sequence
    output = tracker.run_sequence(seq, debug=debug, visdom_info=visdom_info)
  File "../pytracking/evaluation/tracker.py", line 148, in run_sequence
    output = self._track_sequence(tracker, seq, init_info)
  File "../pytracking/evaluation/tracker.py", line 183, in _track_sequence
    self.visualize(image, init_info.get('init_bbox'))
  File "../pytracking/evaluation/tracker.py", line 710, in visualize
    rect = patches.Rectangle((box[0], box[1]), box[2], box[3], linewidth=1, edgecolor=col, facecolor='none')
IndexError: invalid index to scalar variable.

**Comment by HarrisonWu42** [comment]
I have encountered the same problem as you. Have you solved it?

**Comment by Xiantai01** [comment]
I also encountered this problem.
python run_tracker.py atom default --sequence Ironman --debug 1 --use_visdom False --threads 0
Traceback (most recent call last):
  File "run_tracker.py", line 65, in <module>
    main()
  File "run_tracker.py", line 61, in main
    args.threads, {'use_visdom': args.use_visdom, 'server': args.visdom_server, 'port': args.visdom_port})
  File "run_tracker.py", line 37, in run_tracker
    run_dataset(dataset, trackers, debug, threads, visdom_info=visdom_info)
  File "..\pytracking\evaluation\running.py", line 199, in run_dataset
    run_sequence(seq, tracker_info, debug=debug, visdom_info=visdom_info)
  File "..\pytracking\evaluation\running.py", line 148, in run_sequence
    output = tracker.run_sequence(seq, debug=debug, visdom_info=visdom_info)
  File "..\pytracking\evaluation\tracker.py", line 148, in run_sequence
    output = self._track_sequence(tracker, seq, init_info)
  File "..\pytracking\evaluation\tracker.py", line 183, in _track_sequence
    self.visualize(image, init_info.get('init_bbox'))
  File "..\pytracking\evaluation\tracker.py", line 656, in visualize
    rect = patches.Rectangle((box[0], box[1]), box[2], box[3], linewidth=1, edgecolor=col, facecolor='none')
IndexError: invalid index to scalar variable.

**Comment by AustinYuAo** [comment]
I have encountered the same problem. Has anyone solved the problem?
