### ISSUE TITLE
unable to run pytracke for run_video.py 

### ISSUE THREAD

**Issue by FawadAbbas12** [visionml/pytracking#380]
Tracker configuration:
tracker_name: et_tracker
tracker_param: et_tracker

#Error traceback 
tracker weight style: regular
Traceback (most recent call last):
  File "pytracking/run_video.py", line 38, in <module>
    main()
  File "pytracking/run_video.py", line 34, in main
    run_video(args.tracker_name, args.tracker_param,args.videofile, args.optional_box, args.debug, args.save_results)
  File "pytracking/run_video.py", line 20, in run_video
    tracker.run_video(videofilepath=videofile, optional_box=optional_box, debug=debug, save_results=save_results)
  File "pytracking/../pytracking/evaluation/tracker.py", line 311, in run_video
    out = tracker.track(frame)
TypeError: track() missing 1 required positional argument: 'state_input'

**Comment by FawadAbbas12** [comment]
Fixed it by editing code in in following places 
pytracking/evaluation/tracker.py:311
      out = tracker.track(frame)
      to 
      out = tracker.track(frame, out if out else state_dict)
      (better solution will be to make state_dict data member of et_tracker class so that track function's call will be same as old one)
pytracking/tracker/et_tracker/et_tracker.py:180
      state = state_input['previous_output']
      to
      state = state_input
