### ISSUE TITLE
About VOT test on ToMP. 

### ISSUE THREAD

**Issue by Tchuanm** [visionml/pytracking#398]
Hi, all: 
About the test and evaluateion on VOT2020, I get a error for test.
I have create a workspace of it but occur a error as following” 

`(pytracking) ctang@cudahpc03:/datatmp/users/ctang/VITAdapt12/workspace_vot2020$ vot test ToMP50

Generating dummy sequence
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/datatmp/users/ctang/VITAdapt12/pytracking/run_vot.py", line 14, in run_vot2020
    tracker.run_vot2020(debug, visdom_info)
  File "/datatmp/users/ctang/VITAdapt12/pytracking/evaluation/tracker.py", line 674, in run_vot2020
    handle = vot.VOT("rectangle")
  File "/datatmp/users/ctang/VITAdapt12/pytracking/evaluation/vot2020.py", line 70, in __init__
    self._trax = trax.Server([region_format], [trax.Image.PATH], channels, customMetadata=dict(vot="python"))
**TypeError: __init__() got an unexpected keyword argument 'customMetadata'**
Unable to connect to tracker

Traceback (most recent call last):
  File "/home/ctang/miniconda3/envs/pytracking/lib/python3.8/site-packages/vot/utilities/cli.py", line 439, in main
    do_test(args)
  File "/home/ctang/miniconda3/envs/pytracking/lib/python3.8/site-packages/vot/utilities/cli.py", line 92, in do_test
    sequence = DummySequence(50, objects=3 if runtime.multiobject else 1)
  File "/home/ctang/miniconda3/envs/pytracking/lib/python3.8/site-packages/vot/tracker/trax.py", line 539, in multiobject
    self._connect()
  File "/home/ctang/miniconda3/envs/pytracking/lib/python3.8/site-packages/vot/tracker/trax.py", line 549, in _connect
    self._process = TrackerProcess(self._command, self._envvars, log=log, socket=self._socket, timeout=self._timeout)
  File "/home/ctang/miniconda3/envs/pytracking/lib/python3.8/site-packages/vot/tracker/trax.py", line 294, in __init__
    raise e
  File "/home/ctang/miniconda3/envs/pytracking/lib/python3.8/site-packages/vot/tracker/trax.py", line 287, in __init__
    self._client = Client(
  File "/home/ctang/miniconda3/envs/pytracking/lib/python3.8/site-packages/trax/client.py", line 66, in __init__
    raise TraxException("Unable to connect to tracker")
trax.TraxException: Unable to connect to tracker 
`

I test DiMP with commend ` vot test dimp`, there exist the same error,  do you have any idea about it.  Thanks a lot.

**Comment by Tchuanm** [comment]
Hi, 
I have solved the above problem by changing 'customMetadata' to 'metadata' for adapting to vot-toolkit 0.6.3.  However, I meet another error.
`(pytracking) ctang@cudahpc03:/datatmp/users/ctang/VITAdapt12/workspace_vot2020$ vot test tomp
Generating dummy sequence
@@TRAX:hello "trax.name=" "trax.family=" "trax.image=path;" "trax.region=rectangle;" "trax.description=" "trax.version=4" "vot=python" "trax.channels=color;" 
Obtaining runtime for tracker tomp
Initializing tracker
@@TRAX:quit 
@@TRAX:hello "trax.name=" "trax.family=" "trax.image=path;" "trax.region=rectangle;" "trax.description=" "trax.version=4" "vot=python" "trax.channels=color;" 
@@TRAX:initialize "397.0000,183.0000,100.0000,113.0000" 
@@TRAX:frame "file:///tmp/vot_dummy_50_640_480_1/color/00000001.jpg" 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/datatmp/users/ctang/VITAdapt12/pytracking/run_vot.py", line 14, in run_vot2020
    tracker.run_vot2020(debug, visdom_info)
  File "/datatmp/users/ctang/VITAdapt12/pytracking/evaluation/tracker.py", line 674, in run_vot2020
    handle = vot.VOT("rectangle")
  File "/datatmp/users/ctang/VITAdapt12/pytracking/evaluation/vot2020.py", line 74, in __init__
    if isinstance(request.region, trax.Polygon):
AttributeError: 'Request' object has no attribute 'region'`

I am confused about this log and I have no idea how to debug the commend in vscode to solve it.
Looking forward to your help. 
best

**Comment by sewkyz1** [comment]
hello, did you solve this problem?

> Hi, I have solved the above problem by changing 'customMetadata' to 'metadata' for adapting to vot-toolkit 0.6.3. However, I meet another error. `(pytracking) ctang@cudahpc03:/datatmp/users/ctang/VITAdapt12/workspace_vot2020$ vot test tomp
> 
> Generating dummy sequence @@Trax:hello "trax.name=" "trax.family=" "trax.image=path;" "trax.region=rectangle;" "trax.description=" "trax.version=4" "vot=python" "trax.channels=color;" Obtaining runtime for tracker tomp Initializing tracker @@Trax:quit @@Trax:hello "trax.name=" "trax.family=" "trax.image=path;" "trax.region=rectangle;" "trax.description=" "trax.version=4" "vot=python" "trax.channels=color;" @@Trax:initialize "397.0000,183.0000,100.0000,113.0000" @@Trax:frame "file:///tmp/vot_dummy_50_640_480_1/color/00000001.jpg" Traceback (most recent call last): File "", line 1, in File "/datatmp/users/ctang/VITAdapt12/pytracking/run_vot.py", line 14, in run_vot2020 tracker.run_vot2020(debug, visdom_info) File "/datatmp/users/ctang/VITAdapt12/pytracking/evaluation/tracker.py", line 674, in run_vot2020 handle = vot.VOT("rectangle") File "/datatmp/users/ctang/VITAdapt12/pytracking/evaluation/vot2020.py", line 74, in **init** if isinstance(request.region, trax.Polygon): AttributeError: 'Request' object has no attribute 'region'`
> 
> I am confused about this log and I have no idea how to debug the commend in vscode to solve it. Looking forward to your help. best

**Comment by Tchuanm** [comment]
Due to the adaptation of VOTS2023 challenge, VOT2020 evaluatetion has some bugs, you can check the vot-toolkit issues about it. So now we can just waitting.
