### ISSUE TITLE
How to deal with " raise RuntimeError(message) from e         RuntimeError: Error building extension '_prroi_pooling"

### ISSUE THREAD

**Issue by Destroy95** [visionml/pytracking#402]
ubuntu20.04 +cuda11.7+GPU A6000 ADA
```
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/pytracking/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1906, in _run_ninja_build
    env=env)
  File "/home/ubuntu/anaconda3/envs/pytracking/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/pytracking/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/ubuntu/anaconda3/envs/pytracking/lib/python3.7/multiprocessing/pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "../pytracking/evaluation/running.py", line 148, in run_sequence
    output = tracker.run_sequence(seq, debug=debug, visdom_info=visdom_info)
  File "../pytracking/evaluation/tracker.py", line 148, in run_sequence
    output = self._track_sequence(tracker, seq, init_info)
  File "../pytracking/evaluation/tracker.py", line 186, in _track_sequence
    out = tracker.initialize(image, init_info)
  File "../pytracking/tracker/atom/atom.py", line 115, in initialize
    self.init_iou_net()
  File "../pytracking/tracker/atom/atom.py", line 694, in init_iou_net
    target_feat = self.iou_predictor.get_modulation(iou_backbone_features, target_boxes)
  File "../ltr/models/bbreg/atom_iou_net.py", line 157, in get_modulation
    roi3r = self.prroi_pool3r(c3_r, roi1)
  File "/home/ubuntu/anaconda3/envs/pytracking/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "../ltr/external/PreciseRoIPooling/pytorch/prroi_pool/prroi_pool.py", line 28, in forward
    return prroi_pool2d(features, rois, self.pooled_height, self.pooled_width, self.spatial_scale)
  File "../ltr/external/PreciseRoIPooling/pytorch/prroi_pool/functional.py", line 44, in forward
    _prroi_pooling = _import_prroi_pooling()
  File "../ltr/external/PreciseRoIPooling/pytorch/prroi_pool/functional.py", line 33, in _import_prroi_pooling
    verbose=True
  File "/home/ubuntu/anaconda3/envs/pytracking/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1296, in load
    keep_intermediates=keep_intermediates)
  File "/home/ubuntu/anaconda3/envs/pytracking/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1518, in _jit_compile
    is_standalone=is_standalone)
  File "/home/ubuntu/anaconda3/envs/pytracking/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1626, in _write_ninja_file_and_build_library
    error_prefix=f"Error building extension '{name}'")
  File "/home/ubuntu/anaconda3/envs/pytracking/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1916, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension '_prroi_pooling'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "run_tracker.py", line 65, in <module>
    main()
  File "run_tracker.py", line 61, in main
    args.threads, {'use_visdom': args.use_visdom, 'server': args.visdom_server, 'port': args.visdom_port})
  File "run_tracker.py", line 37, in run_tracker
    run_dataset(dataset, trackers, debug, threads, visdom_info=visdom_info)
  File "../pytracking/evaluation/running.py", line 203, in run_dataset
    pool.starmap(run_sequence, param_list)
  File "/home/ubuntu/anaconda3/envs/pytracking/lib/python3.7/multiprocessing/pool.py", line 276, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/home/ubuntu/anaconda3/envs/pytracking/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
RuntimeError: Error building extension '_prroi_pooling'
(pytracking) ubuntu@ubuntu:~/Code/pytracking/pytracking$ 

```

**Comment by immhj** [comment]
same error

**Comment by immhj** [comment]
i think it’s the version problem，maybe change another cuda version or pytorch version can solve this problem
