### ISSUE TITLE
No matching checkpoint file found

### ISSUE THREAD

**Issue by Obadahheyari** [visionml/pytracking#423]
i keep getting this error and dont know how to solve it 

Traceback (most recent call last):
  File "/home/obadah/Desktop/trackers/pytracking/run_webcam.py", line 41, in <module>
    main()
  File "/home/obadah/Desktop/trackers/pytracking/run_webcam.py", line 37, in main
    run_webcam(args.tracker_name, args.tracker_param, args.debug, visdom_info)
  File "/home/obadah/Desktop/trackers/pytracking/run_webcam.py", line 22, in run_webcam
    tracker.run_video_generic(debug=debug, visdom_info=visdom_info)
  File "/home/obadah/Desktop/trackers/pytracking/pytracking/evaluation/tracker.py", line 285, in run_video_generic
    tracker = MultiObjectWrapper(self.tracker_class, params, self.visdom, fast_load=True)
  File "/home/obadah/Desktop/trackers/pytracking/pytracking/evaluation/multi_object_wrapper.py", line 21, in __init__
    self.tracker_copy.initialize_features()
  File "/home/obadah/Desktop/trackers/pytracking/pytracking/tracker/tomp/tomp.py", line 22, in initialize_features
    self.params.net.initialize()
  File "/home/obadah/Desktop/trackers/pytracking/pytracking/features/net_wrappers.py", line 53, in initialize
    super().initialize()
  File "/home/obadah/Desktop/trackers/pytracking/pytracking/features/net_wrappers.py", line 37, in initialize
    self.load_network()
  File "/home/obadah/Desktop/trackers/pytracking/pytracking/features/net_wrappers.py", line 31, in load_network
    self.net = load_network(self.net_path, **self.net_kwargs)
  File "/home/obadah/Desktop/trackers/pytracking/pytracking/utils/loading.py", line 31, in load_network
    net, _ = ltr_loading.load_network(path_full, **kwargs)
  File "/home/obadah/Desktop/trackers/pytracking/ltr/admin/loading.py", line 62, in load_network
    raise Exception('No matching checkpoint file found')
Exception: No matching checkpoint file found

**Comment by AbdallahOmarAhmed** [comment]
you need to download the checkpoint from model zoo
