### ISSUE TITLE
TypeError: list indices must be integers or slices, not str

### ISSUE THREAD

**Issue by L1690941806** [visionml/pytracking#431]
when I trained the model, I met the following problem. How can I solve it?

Traceback (most recent call last):
  File "D:/py-program/pytracking/ltr/run_training.py", line 55, in <module>
    main()
  File "D:/py-program/pytracking/ltr/run_training.py", line 50, in main
    run_training(args.train_module, args.train_name, args.cudnn_benchmark)
  File "D:/py-program/pytracking/ltr/run_training.py", line 39, in run_training
    expr_func(settings)
  File "D:\py-program\pytracking\ltr\train_settings\tamos\tamos_resnet50.py", line 67, in run
    imagenetvid_train = ImagenetVIDMOT(settings.env.imagenet_vid_gmot_dir, split='train')
  File "D:\py-program\pytracking\ltr\dataset\imagenetvid_mot.py", line 31, in __init__
    self.sequence_list, self.num_tracks_per_seq = data['seq_list'], data['num_tracks']
TypeError: list indices must be integers or slices, not str

**Comment by matteo-dunnhofer** [comment]
Hi @L1690941806 

where did you find the `ImageNet-Vid.json` file needed in line https://github.com/visionml/pytracking/blob/1f3c31e06aae6ffaae993f546cc8f103f9017ea9/ltr/dataset/imagenetvid_mot.py#L22 ?
