### ISSUE TITLE
ModuleNotFoundError: No module named 'ltr.admin.local'

### ISSUE THREAD

**Issue by kassimi98** [visionml/pytracking#432]
Traceback (most recent call last):
  File "/content/pytracking/pytracking/run_video.py", line 38, in <module>
    main()
  File "/content/pytracking/pytracking/run_video.py", line 34, in main
    run_video(args.tracker_name, args.tracker_param,args.videofile, args.optional_box, args.debug, args.save_results)
  File "/content/pytracking/pytracking/run_video.py", line 20, in run_video
    tracker.run_video_generic(videofilepath=videofile, optional_box=optional_box, debug=debug, save_results=save_results)
  File "/content/pytracking/pytracking/../pytracking/evaluation/tracker.py", line 283, in run_video_generic
    tracker.initialize_features()
  File "/content/pytracking/pytracking/../pytracking/tracker/tamos/tamos.py", line 34, in initialize_features
    self.params.net.initialize()
  File "/content/pytracking/pytracking/../pytracking/features/net_wrappers.py", line 53, in initialize
    super().initialize()
  File "/content/pytracking/pytracking/../pytracking/features/net_wrappers.py", line 37, in initialize
    self.load_network()
  File "/content/pytracking/pytracking/../pytracking/features/net_wrappers.py", line 31, in load_network
    self.net = load_network(self.net_path, **self.net_kwargs)
  File "/content/pytracking/pytracking/../pytracking/utils/loading.py", line 31, in load_network
    net, _ = ltr_loading.load_network(path_full, **kwargs)
  File "/content/pytracking/pytracking/../ltr/admin/loading.py", line 79, in load_network
    checkpoint_dict = torch_load_legacy(checkpoint_path)
  File "/content/pytracking/pytracking/../ltr/admin/loading.py", line 125, in torch_load_legacy
    checkpoint_dict = torch.load(path, map_location='cpu')
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 1025, in load
    return _load(opened_zipfile,
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 1446, in _load
    result = unpickler.load()
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 1439, in find_class
    return super().find_class(mod_name, name)
ModuleNotFoundError: No module named 'ltr.admin.local'

**Comment by 2006pmach** [comment]
Please read the readme and the installation instructions.
