### ISSUE TITLE
Can not compile Precision Pooling library.

### ISSUE THREAD

**Issue by QIQIVTrackingY** [visionml/pytracking#58]
Tracker: atom default 0 ,  Sequence: Basketball
/home/dl/anaconda3/lib/python3.7/site-packages/torch/nn/functional.py:2539: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
Using /tmp/torch_extensions as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /tmp/torch_extensions/_prroi_pooling/build.ninja...
Building extension module _prroi_pooling...
[1/3] c++ -MMD -MF prroi_pooling_gpu.o.d -DTORCH_EXTENSION_NAME=_prroi_pooling -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/dl/anaconda3/lib/python3.7/site-packages/torch/include -isystem /home/dl/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -isystem /home/dl/anaconda3/lib/python3.7/site-packages/torch/include/TH -isystem /home/dl/anaconda3/lib/python3.7/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /home/dl/anaconda3/include/python3.7m -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++11 -c /home/dl/qiqi/pytracking-master/ltr/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu.c -o prroi_pooling_gpu.o
[2/3] /usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=_prroi_pooling -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/dl/anaconda3/lib/python3.7/site-packages/torch/include -isystem /home/dl/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -isystem /home/dl/anaconda3/lib/python3.7/site-packages/torch/include/TH -isystem /home/dl/anaconda3/lib/python3.7/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /home/dl/anaconda3/include/python3.7m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' -std=c++11 -c /home/dl/qiqi/pytracking-master/ltr/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu_impl.cu -o prroi_pooling_gpu_impl.cuda.o
[3/3] c++ prroi_pooling_gpu.o prroi_pooling_gpu_impl.cuda.o -shared -L/usr/local/cuda/lib64 -lcudart -o _prroi_pooling.so
Loading extension module _prroi_pooling...
Can not compile Precise RoI Pooling library.

**Comment by martin-danelljan** [comment]
Hi. Can you provide details of your environment. Are you using the latest version of pytorch?

**Comment by QIQIVTrackingY** [comment]
I use python3.7, pytorch1.1.0, cuda9.1.



---Original---

**Comment by QIQIVTrackingY** [comment]
I have sloved the problem. But when i use ''conda install pytorch torchvision '' to install pytorch, i got Illegal instruction (core dumped). Then I use pip install pytorch and I got 
 Traceback (most recent call last):
  File "run_tracker.py", line 78, in <module>
    main()
  File "run_tracker.py", line 74, in main
    run_tracker(args.tracker_name, args.tracker_param, args.runid, args.dataset, args.sequence, args.debug, args.threads)
  File "run_tracker.py", line 57, in run_tracker
    trackers = [Tracker(tracker_name, tracker_param, run_id)]
  File "../pytracking/evaluation/tracker.py", line 31, in __init__
    self.parameters = self.get_parameters()
  File "../pytracking/evaluation/tracker.py", line 104, in get_parameters
    param_module = importlib.import_module('pytracking.parameter.{}.{}'.format(self.name, self.parameter_name))  #pytracking.parameter.atom.default
  File "/home/dl/anaconda3/envs/pytracking/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "../pytracking/parameter/atom/default.py", line 3, in <module>
    from pytracking.features import deep
  File "../pytracking/features/deep.py", line 3, in <module>
    import torchvision
  File "/home/dl/anaconda3/envs/pytracking/lib/python3.7/site-packages/torchvision/__init__.py", line 1, in <module>
    from torchvision import models
  File "/home/dl/anaconda3/envs/pytracking/lib/python3.7/site-packages/torchvision/models/__init__.py", line 11, in <module>
    from . import detection
  File "/home/dl/anaconda3/envs/pytracking/lib/python3.7/site-packages/torchvision/models/detection/__init__.py", line 1, in <module>
    from .faster_rcnn import *
  File "/home/dl/anaconda3/envs/pytracking/lib/python3.7/site-packages/torchvision/models/detection/faster_rcnn.py", line 7, in <module>
    from torchvision.ops import misc as misc_nn_ops
  File "/home/dl/anaconda3/envs/pytracking/lib/python3.7/site-packages/torchvision/ops/__init__.py", line 1, in <module>
    from .boxes import nms, box_iou
  File "/home/dl/anaconda3/envs/pytracking/lib/python3.7/site-packages/torchvision/ops/boxes.py", line 2, in <module>
    from torchvision import _C
ImportError: /home/dl/anaconda3/envs/pytracking/lib/python3.7/site-packages/torchvision/_C.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN3c107Warning4warnENS_14SourceLocationENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE

**Comment by martin-danelljan** [comment]
Could you please try with CUDA 10, if that is supported by your OS?
