### ISSUE TITLE
Install Errors: ModuleNotFoundError: No module named 'torch' in Anaconda env pytracking

### ISSUE THREAD

**Issue by fybaft2012** [visionml/pytracking#70]
Hi @goutamgmb and @martin-danelljan 
Thank you for your excellent works. I tried to install pytracking framework on my Ubuntu 16.04 with Anaconda 3 already installed. I use the command provided "bash install.sh my_Anaconda_install_path pytracking". There is a strange error when it went to 

****************** Setting up environment ******************
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/aiserver/pytracking/pytracking/__init__.py", line 1, in <module>
    from pytracking.libs import TensorList, TensorDict
  File "/home/aiserver/pytracking/pytracking/libs/__init__.py", line 1, in <module>
    from .tensorlist import TensorList
  File "/home/aiserver/pytracking/pytracking/libs/tensorlist.py", line 2, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/aiserver/fangyang/SiamMask/pytracking/ltr/__init__.py", line 1, in <module>
    from .admin.loading import load_network
  File "/home/aiserver/fangyang/SiamMask/pytracking/ltr/admin/loading.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
*****************************************************************
I found that torch was installed in Anaconda base env, but not in newly created pytracking env (using python import torch test). Would you help me with this problem?

**Comment by fybaft2012** [comment]
I found the solution, I should use "sudo bash install.sh my_Anaconda_install_path pytracking". installation is successfully. I will close this issue.
