### ISSUE TITLE
test error

### ISSUE THREAD

**Issue by yongwuSHU** [visionml/pytracking#78]
"Traceback (most recent call last):
  File "../pytracking/evaluation/otbdataset.py", line 60, in _construct_sequence
    ground_truth_rect = np.loadtxt(str(anno_path), dtype=np.float64)
  File "/home/yongwu/anaconda3/envs/mx/lib/python3.7/site-packages/numpy/lib/npyio.py", line 1141, in loadtxt
    for x in read_data(_loadtxt_chunksize):
  File "/home/yongwu/anaconda3/envs/mx/lib/python3.7/site-packages/numpy/lib/npyio.py", line 1068, in read_data
    items = [conv(val) for (conv, val) in zip(converters, vals)]
  File "/home/yongwu/anaconda3/envs/mx/lib/python3.7/site-packages/numpy/lib/npyio.py", line 1068, in <listcomp>
    items = [conv(val) for (conv, val) in zip(converters, vals)]
  File "/home/yongwu/anaconda3/envs/mx/lib/python3.7/site-packages/numpy/lib/npyio.py", line 775, in floatconv
    return float(x)
ValueError: could not convert string to float: '250,168,106,105'
"
sorry to bother,how can i fix that? thank you.

**Comment by yongwuSHU** [comment]
when i use "python run_tracker.py atom --dataset otb default" to test, cause this error.

**Comment by Cassiel829** [comment]
Hi, I met the same problem, could you please tell me how to solve this problem? Thanks

**Comment by yongwuSHU** [comment]
your dataset OTB had a problem that some ground truth format are wrong, like some coordinate values have no commas .Please check carefully! @Cassiel829
