### ISSUE TITLE
OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.

### ISSUE THREAD

**Issue by salt-fisher** [visionml/pytracking#81]
my os is ubuntu18.04 and my gpu is 1080 
create the conda env and install all package as your instructions
and torch.cuda.is_available is True.but i got a error like this:

No matching checkpoint file found
Using /tmp/torch_extensions as PyTorch extensions root...
Detected CUDA files, patching ldflags
Training crashed at epoch 1
Traceback (most recent call last):
  File "run_training.py", line 55, in <module>
    main()
  File "run_training.py", line 50, in main
    run_training(args.train_module, args.train_name, args.cudnn_benchmark)
  File "run_training.py", line 39, in run_training
    expr_func(settings)
  File "../ltr/train_settings/bbreg/atom_default.py", line 105, in run
    trainer.train(45, load_latest=True, fail_safe=False)
  File "../ltr/trainers/base_trainer.py", line 71, in train
    self.train_epoch()
  File "../ltr/trainers/ltr_trainer.py", line 76, in train_epoch
    self.cycle_dataset(loader)
  File "../ltr/trainers/ltr_trainer.py", line 57, in cycle_dataset
    loss, stats = self.actor(data)
  File "../ltr/actors/bbreg.py", line 17, in __call__
    iou_pred = self.net(data['train_images'], data['test_images'], data['train_anno'], data['test_proposals'])
  File "/home/lcq/anaconda3/envs/pytracking/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "../ltr/models/bbreg/atom.py", line 47, in forward
    test_proposals.view(num_train_images, num_sequences, -1, 4))
  File "/home/lcq/anaconda3/envs/pytracking/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "../ltr/models/bbreg/atom_iou_net.py", line 86, in forward
    modulation = self.get_modulation(feat1, bb1)
  File "../ltr/models/bbreg/atom_iou_net.py", line 157, in get_modulation
    roi3r = self.prroi_pool3r(c3_r, roi1)
  File "/home/lcq/anaconda3/envs/pytracking/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "../ltr/external/PreciseRoIPooling/pytorch/prroi_pool/prroi_pool.py", line 28, in forward
    return prroi_pool2d(features, rois, self.pooled_height, self.pooled_width, self.spatial_scale)
  File "../ltr/external/PreciseRoIPooling/pytorch/prroi_pool/functional.py", line 44, in forward
    _prroi_pooling = _import_prroi_pooling()
  File "../ltr/external/PreciseRoIPooling/pytorch/prroi_pool/functional.py", line 33, in _import_prroi_pooling
    verbose=True
  File "/home/lcq/anaconda3/envs/pytracking/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 658, in load
    is_python_module)
  File "/home/lcq/anaconda3/envs/pytracking/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 827, in _jit_compile
    with_cuda=with_cuda)
  File "/home/lcq/anaconda3/envs/pytracking/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 861, in _write_ninja_file_and_build
    verbose)
  File "/home/lcq/anaconda3/envs/pytracking/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 923, in _prepare_ldflags
    extra_ldflags.append('-L{}'.format(_join_cuda_home('lib64')))
  File "/home/lcq/anaconda3/envs/pytracking/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1146, in _join_cuda_home
    raise EnvironmentError('CUDA_HOME environment variable is not set. '
OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.

how to solve the problem?

**Comment by martin-danelljan** [comment]
Hi. Check [this response](https://github.com/visionml/pytracking/issues/67#issuecomment-531319465). Maybe it helps.

**Comment by salt-fisher** [comment]
thanks a lot!!!!!

**Comment by 1458763783** [comment]
I encountered the same mistake. Have you solved this problem?
