### ISSUE TITLE
RuntimeError: Error building extension '_prroi_pooling'

### ISSUE THREAD

**Issue by ZZXin16** [visionml/pytracking#92]
Hi,
When I config the environment,I meet with the questions:
(apytracking) amax@amax:~/Desktop/sunlinna/apytracking/pytracking$ python run_webcam.py dimp dimp50
/home/amax/anaconda3/envs/apytracking/lib/python3.7/site-packages/torch/nn/functional.py:2494: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
Using /tmp/torch_extensions as PyTorch extensions root...
/home/amax/anaconda3/envs/apytracking/lib/python3.7/site-packages/torch/utils/cpp_extension.py:197: UserWarning: 

                               !! WARNING !!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Your compiler (c++ 4.8) may be ABI-incompatible with PyTorch!
Please use a compiler that is ABI-compatible with GCC 4.9 and above.
See https://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html.

See https://gist.github.com/goldsborough/d466f43e8ffc948ff92de7486c5216d6
for instructions on how to install GCC 4.9 or higher.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

                              !! WARNING !!

  warnings.warn(ABI_INCOMPATIBILITY_WARNING.format(compiler))
Detected CUDA files, patching ldflags
Emitting ninja build file /tmp/torch_extensions/_prroi_pooling/build.ninja...
Building extension module _prroi_pooling...
[1/3] /usr/local/cuda-10.0/:/usr/local/cuda-10.0/bin/nvcc -DTORCH_EXTENSION_NAME=_prroi_pooling -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/amax/anaconda3/envs/apytracking/lib/python3.7/site-packages/torch/include -isystem /home/amax/anaconda3/envs/apytracking/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -isystem /home/amax/anaconda3/envs/apytracking/lib/python3.7/site-packages/torch/include/TH -isystem /home/amax/anaconda3/envs/apytracking/lib/python3.7/site-packages/torch/include/THC -isystem /usr/local/cuda-10.0/:/usr/local/cuda-10.0/include -isystem /home/amax/anaconda3/envs/apytracking/include/python3.7m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_61,code=sm_61 --compiler-options '-fPIC' -std=c++11 -c /home/amax/Desktop/sunlinna/apytracking/ltr/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu_impl.cu -o prroi_pooling_gpu_impl.cuda.o
FAILED: prroi_pooling_gpu_impl.cuda.o 
/usr/local/cuda-10.0/:/usr/local/cuda-10.0/bin/nvcc -DTORCH_EXTENSION_NAME=_prroi_pooling -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/amax/anaconda3/envs/apytracking/lib/python3.7/site-packages/torch/include -isystem /home/amax/anaconda3/envs/apytracking/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -isystem /home/amax/anaconda3/envs/apytracking/lib/python3.7/site-packages/torch/include/TH -isystem /home/amax/anaconda3/envs/apytracking/lib/python3.7/site-packages/torch/include/THC -isystem /usr/local/cuda-10.0/:/usr/local/cuda-10.0/include -isystem /home/amax/anaconda3/envs/apytracking/include/python3.7m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_61,code=sm_61 --compiler-options '-fPIC' -std=c++11 -c /home/amax/Desktop/sunlinna/apytracking/ltr/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu_impl.cu -o prroi_pooling_gpu_impl.cuda.o
/bin/sh: 1: /usr/local/cuda-10.0/:/usr/local/cuda-10.0/bin/nvcc: not found
[2/3] c++ -MMD -MF prroi_pooling_gpu.o.d -DTORCH_EXTENSION_NAME=_prroi_pooling -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/amax/anaconda3/envs/apytracking/lib/python3.7/site-packages/torch/include -isystem /home/amax/anaconda3/envs/apytracking/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -isystem /home/amax/anaconda3/envs/apytracking/lib/python3.7/site-packages/torch/include/TH -isystem /home/amax/anaconda3/envs/apytracking/lib/python3.7/site-packages/torch/include/THC -isystem /usr/local/cuda-10.0/:/usr/local/cuda-10.0/include -isystem /home/amax/anaconda3/envs/apytracking/include/python3.7m -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++11 -c /home/amax/Desktop/sunlinna/apytracking/ltr/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu.c -o prroi_pooling_gpu.o
FAILED: prroi_pooling_gpu.o 
c++ -MMD -MF prroi_pooling_gpu.o.d -DTORCH_EXTENSION_NAME=_prroi_pooling -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/amax/anaconda3/envs/apytracking/lib/python3.7/site-packages/torch/include -isystem /home/amax/anaconda3/envs/apytracking/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -isystem /home/amax/anaconda3/envs/apytracking/lib/python3.7/site-packages/torch/include/TH -isystem /home/amax/anaconda3/envs/apytracking/lib/python3.7/site-packages/torch/include/THC -isystem /usr/local/cuda-10.0/:/usr/local/cuda-10.0/include -isystem /home/amax/anaconda3/envs/apytracking/include/python3.7m -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++11 -c /home/amax/Desktop/sunlinna/apytracking/ltr/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu.c -o prroi_pooling_gpu.o
In file included from /home/amax/anaconda3/envs/apytracking/lib/python3.7/site-packages/torch/include/ATen/cuda/CUDAContext.h:5:0,
                 from /home/amax/Desktop/sunlinna/apytracking/ltr/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu.c:15:
/home/amax/anaconda3/envs/apytracking/lib/python3.7/site-packages/torch/include/c10/cuda/CUDAStream.h:6:30: fatal error: cuda_runtime_api.h: 没有那个文件或目录
 #include <cuda_runtime_api.h>
                              ^
compilation terminated.
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/amax/anaconda3/envs/apytracking/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1030, in _build_extension_module
    check=True)
  File "/home/amax/anaconda3/envs/apytracking/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_webcam.py", line 41, in <module>
    main()
  File "run_webcam.py", line 37, in main
    run_webcam(args.tracker_name, args.tracker_param, args.debug, visdom_info)
  File "run_webcam.py", line 22, in run_webcam
    tracker.run_webcam(debug, visdom_info)
  File "../pytracking/evaluation/tracker.py", line 101, in run_webcam
    tracker.track_webcam()
  File "../pytracking/tracker/base/basetracker.py", line 252, in track_webcam
    self.initialize(frame, {'init_bbox': init_state})
  File "../pytracking/tracker/dimp/dimp.py", line 70, in initialize
    self.init_classifier(init_backbone_feat)
  File "../pytracking/tracker/dimp/dimp.py", line 514, in init_classifier
    compute_losses=plot_loss)
  File "../ltr/models/target_classifier/linear_filter.py", line 99, in get_filter
    weights = self.filter_initializer(feat, bb)
  File "/home/amax/anaconda3/envs/apytracking/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "../ltr/models/target_classifier/initializer.py", line 161, in forward
    weights = self.filter_pool(feat, bb)
  File "/home/amax/anaconda3/envs/apytracking/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "../ltr/models/target_classifier/initializer.py", line 45, in forward
    return self.prroi_pool(feat, roi1)
  File "/home/amax/anaconda3/envs/apytracking/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "../ltr/external/PreciseRoIPooling/pytorch/prroi_pool/prroi_pool.py", line 28, in forward
    return prroi_pool2d(features, rois, self.pooled_height, self.pooled_width, self.spatial_scale)
  File "../ltr/external/PreciseRoIPooling/pytorch/prroi_pool/functional.py", line 44, in forward
    _prroi_pooling = _import_prroi_pooling()
  File "../ltr/external/PreciseRoIPooling/pytorch/prroi_pool/functional.py", line 33, in _import_prroi_pooling
    verbose=True
  File "/home/amax/anaconda3/envs/apytracking/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 661, in load
    is_python_module)
  File "/home/amax/anaconda3/envs/apytracking/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 830, in _jit_compile
    with_cuda=with_cuda)
  File "/home/amax/anaconda3/envs/apytracking/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 883, in _write_ninja_file_and_build
    _build_extension_module(name, build_directory, verbose)
  File "/home/amax/anaconda3/envs/apytracking/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1043, in _build_extension_module
    raise RuntimeError(message)
RuntimeError: Error building extension '_prroi_pooling'
my package version:torch 1.3.1 torchvision 0.4.2
 NVIDIA-SMI 430.50       Driver Version: 430.50       CUDA Version: 10.1 
How can I solve it?

**Comment by martin-danelljan** [comment]
Hi. Probably its a problem with your GCC version as the warning says. Try install a newer GCC or just a newer version of Linux.
